10 спринт: создать rest-сервис с пользователями и фильмами
elistratov-av/java-filmorate pull request #2
Opened 2024-07-12 10:39 UTC by elistratov-av

2024-07-12 18:03 UTC, sergeymamonov requested changes

2024-07-12 19:46 UTC, elistratov-av commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static final LocalDate MOVIE_BIRTHDAY = LocalDate.of(1895, Month.DECEMBER, 28);
перенес на самый верх

2024-07-12 19:52 UTC, elistratov-av commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        try {
try/catch организовал ради логирования ошибок валидации
если перенести логирование внутрь веток if, то будет дублирование кода
не знаю конечно как в Java, но в других языках обработка исключений абсолютно не затратная вещь
готов избавиться от блока try/catch, но как быть с логированием в таком случае ?

2024-07-13 09:55 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        try {
Логирование можно вставить в конструктор ошибки.
В Java если уж и нужно вставлять try/catch, то помещать в него только тот, код, который может кинуть ошибку. Потому что код внутри этого оператора выполняется медленее.

2024-07-13 10:31 UTC, merged