групповой проект
elistratov-av/java-filmorate pull request #25
Opened 2024-09-10 19:45 UTC by elistratov-av

2024-09-11 19:59 UTC, sergeymamonov requested changes

2024-09-11 19:59 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +    // GET /directors
Я бы не делал таких комментариев. И так понятен метод и путь.

2024-09-11 19:59 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public Collection<Feed> getFeed(@PathVariable int id) {
Collection это слишком общий комментарий, тут может быть и множество и список. Лучше сузить до более конкретного интерфейса.

2024-09-11 19:59 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/dal/impl/JdbcFilmRepository.java
> +import ru.yandex.practicum.filmorate.model.*;
Не нужно импортировать через *

2024-09-11 19:59 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/dal/impl/JdbcFilmRepository.java
> +    private static HashMap<Integer, List<Film>> mapSetToHashMap(ResultSet rs) throws SQLException {
Лучше возвращайте интерфейс.

2024-09-11 19:59 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/dal/impl/JdbcFilmRepository.java
> +        HashMap<Integer, LinkedHashMap<Integer, Film>> userWithFilms = new LinkedHashMap<>();
Почему именно такой тип мапы выбрали, а не обычную хеш мапу?

2024-09-11 19:59 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/FilmServiceImpl.java
> +                throw new ValidationException("Режиссеры не найдены");
Название ValidationException говорит, что исключение может возникнуть из-за некорректных входных данных. А тут не нашли что-то в БД и возникает эта ошибка.

2024-09-11 20:13 UTC, elistratov-av commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +    // GET /directors
такие комментарии обычно пишут в самом начале и они удобны для правильного описания параметров метода контроллера

2024-09-11 20:14 UTC, elistratov-av commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public Collection<Feed> getFeed(@PathVariable int id) {
Заменили на List, но в контроллере это не принципиально, все равно любой интерфейс преобразуется в json массив

2024-09-11 20:23 UTC, elistratov-av commented on src/main/java/ru/yandex/practicum/filmorate/dal/impl/JdbcFilmRepository.java
> +    private static HashMap<Integer, List<Film>> mapSetToHashMap(ResultSet rs) throws SQLException {
переделали

2024-09-11 20:30 UTC, elistratov-av commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/FilmServiceImpl.java
> +                throw new ValidationException("Режиссеры не найдены");
ValidationException мапится на 400 ошибку, а проверка по смыслу именно валидация данных и означает, что в переданных данных присутствуют некорректные id (в данном случае режиссеров), если смущает слово не найдены, то можно заменить на что-нибудь - присутствуют некорректные ссылки на режисеров, ну или как-то еще по литературнее...

2024-09-11 20:51 UTC, elistratov-av commented on src/main/java/ru/yandex/practicum/filmorate/dal/impl/JdbcFilmRepository.java
> +        HashMap<Integer, LinkedHashMap<Integer, Film>> userWithFilms = new LinkedHashMap<>();
использовали LinkedHashMap на автомате по аналогии с другими вариантами, где был важен порядок, а здесь она действительно лишняя

2024-09-11 22:21 UTC, Sheikhovskiy commented on src/main/java/ru/yandex/practicum/filmorate/dal/impl/JdbcFilmRepository.java
> +        HashMap<Integer, LinkedHashMap<Integer, Film>> userWithFilms = new LinkedHashMap<>();
Предыдущая реализация public List<Film> getRecommendedFilms( int id) основалась на алгоритме, описанном на сайте, приложенном в задаче add-recommendations.
Изначально я планировал хранить в HashMap'е id пользователя и список лайкнутых им фильмов.
Но, в реализации id пользователя не понадобились. Переделал метод без HashMap.

2024-09-13 04:00 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +    // GET /directors
Комментарии необходимы только там, где по коду не объясняет происходящего. Например, добавлена ссылка на документацию. Здесь же дублирование информации, то, что это метод get понятно из аннотации @GetMapping, что к ресурсу directors - понятно из @RequestMapping("/directors"). Поэтому нет необходимости в этих комментариях. Код должен быть самодокументируемым. Об этом можно поискать и почитать в интернете.

2024-09-13 04:03 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +import org.springframework.web.bind.annotation.*;
Необходимо заменить все импорты через *.

2024-09-13 04:03 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/FilmServiceImpl.java
> +                throw new ValidationException("Режиссеры не найдены");
если что-то не нашли, то это 404 NotFound. Поэтому здесь и в аналогичных местах должна быть ошибка, которая потом мапится в 404.

2024-09-13 04:03 UTC, sergeymamonov approved these changes

2024-09-13 09:54 UTC, vlad-iv approved these changes

2024-09-13 09:55 UTC, vlad-iv approved these changes
Ок

2024-09-13 10:05 UTC, merged