12 спринт: добавить работу с БД
elistratov-av/java-filmorate pull request #5
Opened 2024-08-22 20:57 UTC by elistratov-av

2024-08-24 08:10 UTC, sergeymamonov requested changes
Посмотрите везде запросы SELECT * FROM .... Такие запросы опасны и без необходимости их не делать.

2024-08-24 08:10 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/dal/JdbcUserRepository.java
> +        return jdbc.query(FIND_ALL_QUERY,
А действительно нужен такой запрос? Если таблица большая и запрос всей таблицы может снизить производительность БД и, как следствие, всего приложения.

2024-08-24 08:10 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/UserServiceImpl.java
> +        //userRepository.addFriend(friend, user);
Не оставляйте закомментированного кода.

2024-08-24 10:04 UTC, elistratov-av commented on src/main/java/ru/yandex/practicum/filmorate/dal/JdbcFilmRepository.java
> +            SELECT f.*, m.name mpa_name, g.genre_id, g.name genre_name
заменил везде на явное указание полей, но непонятно чем это лучше, любое изменение полей в БД в любом случае приведет к ошибке, в случае с полным указанием полей на этапе запроса или при использовании звездочки на этапе маппинга результатов, но код без звездочки получается более многословным

2024-08-24 10:05 UTC, elistratov-av commented on src/main/java/ru/yandex/practicum/filmorate/dal/JdbcFilmRepository.java
> +    private static final String INSERT_QUERY = "INSERT INTO films (name, description, release_date, duration, mpa_id) VALUES(:name, :desc, :rel_date, :duration, :mpa_id)";
отформатировал все запросы заново

2024-08-24 10:05 UTC, elistratov-av commented on src/main/java/ru/yandex/practicum/filmorate/dal/JdbcUserRepository.java
> +        return jdbc.query(FIND_ALL_QUERY,
по заданию нужен, поэтому и написал его

2024-08-24 10:12 UTC, elistratov-av commented on src/main/java/ru/yandex/practicum/filmorate/service/UserServiceImpl.java
> +        //userRepository.addFriend(friend, user);
убрал куски ненужного кода

2024-08-25 11:57 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/dal/JdbcFilmRepository.java
> +            SELECT f.*, m.name mpa_name, g.genre_id, g.name genre_name
Во-первых, не всегда нужны все поля, и лучше явно запрашивать только те поля, которые нужны. Во-вторых, можно добавить поле в БД, но забыть добавить его в маппер или еще где-то в коде. Запрос всех полей через * в таком случае приведет к ошибке. Запрос именнованных полей просто не запросит новое поле. Или еще пример, вы сделали запрос через *, коллеги добавили новое поле и теперь ваш запрос начал отрабатывать медленнее, так как еще выгружает их поле, которое вам не нужно.

2024-08-25 11:59 UTC, sergeymamonov approved these changes

2024-08-25 12:56 UTC, merged